### ISSUE TITLE
Error in whisper_endpoin.predict()

### ISSUE THREAD

**Issue by gani02** [aws-samples/whisper-audio-inference-for-amazon-sagemaker#3]
Hi,

Getting an error in whisper_endpoin.predict()

In logs, I see the following

2023-04-09T13:29:53.758-07:00

2023-04-09T20:29:53,737 [ERROR] Thread-1151 org.pytorch.serve.metrics.MetricCollector - Traceback (most recent call last):
  File "ts/metrics/metric_collector.py", line 27, in <module>
    system_metrics.collect_all(sys.modules['ts.metrics.system_metrics'], arguments.gpu)
  File "/opt/conda/lib/python3.8/site-packages/ts/metrics/system_metrics.py", line 91, in collect_all
    value(num_of_gpu)
  File "/opt/conda/lib/python3.8/site-packages/ts/metrics/system_metrics.py", line 61, in gpu_utilization
    import nvgpu

ModuleNotFoundError: No module named 'nvgpu'

W-9000-model_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker error

There are quite a few warning of worker thread dead but nothing else that warrants attention.

Followed all the steps... not sure what I missed. Any thoughts, what I may be missing?

**Comment by sashakttripathi** [comment]
I am getting the same issue
